name: Ruby Syntax Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  syntax-check:
    name: Syntax Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Install dependencies
      run: gem install erubis

    - name: List PR Files
      id: pr-files
      run: |
        # Get the base commit (the common ancestor between the source and target branches)
        BASE_COMMIT=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | jq -r .base.sha)

        # List the changed files in the PR using the base commit as reference
        PR_FILES=$(git diff --name-only $BASE_COMMIT)

        echo "::set-output name=pr_files::$PR_FILES"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Print PR Files
      run: |
        echo "PR Files:"
        echo "${{ steps.pr-files.outputs.pr_files }}"
