name: Ruby Syntax Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  syntax-check:
    name: Syntax Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Install dependencies
      run: gem install erubis

    - name: Check Ruby syntax
      run: |
        # Find all .rb and .erb files in the repository
        FILES=$(git diff --name-status --staged | grep -v "^D" | sed -e 's/^[MAR]\s*//g' |  egrep "(\.rb)$")

        for file in $FILES; do
          if [[ $file == *.rb ]]; then
            ruby -c "$file"
          elif [[ $file == *.erb ]]; then
            erb -x -T - "$file" | ruby -c
          fi
        done