name: Ruby Syntax Check

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.rb'
      - '**/*.erb'
  push:
    branches:
      - main

jobs:
  syntax-check:
    name: Syntax Check
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Fetch Main Branch
        run: git fetch
        if: ${{ github.event_name == 'pull_request' }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2 # Replace with your preferred Ruby version

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Install dependencies for ERB
        run: gem install erubis

      - name: List Changed Files
        id: changed-files
        run: |
          echo "PR Changed Files:"
          git diff --name-only origin/${{ github.event.pull_request.base.ref }}...origin/${{ github.event.pull_request.head.ref }} > changed_files.txt
          cat changed_files.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Ruby syntax for changed files
        run: |
          changed_files=$(cat changed_files.txt)
          echo "Changed Ruby files in the pull request: $changed_files"
          if [ -n "$changed_files" ]; then
            for file in $changed_files; do
              if [[ $file == *.rb ]]; then
                ruby -c "$file"
              elif [[ $file == *.erb ]]; then
                erb -x -T - "$file" | ruby -c
              fi
            done
          else
            echo "No Ruby or ERB files have changed."
          fi
